// Generated by Skyramp v1.3.27 on 2026-06-23 22:34:06.11846808 +0000 UTC m=+659.187254049
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output field_reorder_persist_reload.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/field_reorder_persist_reload_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(115000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8055/admin/login");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("textbox", { name: "Password" }).press("Enter");
    await page.locator("header").getByRole("link", { exact: true, name: "Data Model" }).click();
    await page.locator("main").getByRole("link", { name: "drag_handle database" }).click();
    await expect(page).toHaveURL(/test_collection/);
    await expect(page.getByRole("heading", { name: "Fields & Layout Saves" })).toHaveText("Fields & Layout Saves Automatically");
    expect(errors).toHaveLength(0);
});
