// Generated by Skyramp v1.3.27 on 2026-06-23 22:30:22.548324996 +0000 UTC m=+435.617110965
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output field_reorder_drag_drop.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/field_reorder_drag_drop_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(530000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.ok()).toBe(true);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/settings/data-model/test_collection");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.mouse.move(327, 259);
    await page.mouse.down();
    await page.mouse.move(327, 170, { steps: 20 });
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/**/**");
    await page.mouse.up();
    const response2 = await responsePromise2;
    expect(response2.ok()).toBe(true);

    await page.waitForTimeout(1500);
    await expect(page.getByRole("heading", { name: "Fields & Layout Saves" })).toHaveText("Fields & Layout Saves Automatically");
    expect(errors).toHaveLength(0);
});
