// Generated by Skyramp v1.3.24 on 2026-06-03 18:48:11.818187508 +0000 UTC m=+510.041860749
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output hash_flow_basic_config_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/hash_flow_basic_config_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(313000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/settings/flows");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await page.getByRole("button", { name: "Create Flow" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.getByRole("button", { name: "Create Flow" }).click();

    const playwrightRequest1: Record<string, any> = {"name": "Hash Test Flow"};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest1, "name"));
    await page.getByRole("button", { name: "arrow_forward" }).click();
    await page.getByRole("button", { name: "touch_app Manual Triggers on" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/flows**");
    await page.getByRole("button", { name: "check" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.click();
    await page.getByRole("button", { name: "tag Hash Generate" }).click();
    await expect(page.getByRole("button", { name: "tag Hash Generate" })).toContainText("Hash");
    await expect(page.getByRole("textbox", { name: "Enter the value to hash..." })).toBeVisible();

    const playwrightRequest2: Record<string, any> = {"operation": {"options": {"value": "hello world"}}};

    await page.getByRole("textbox", { name: "Enter the value to hash..." }).fill(getValue(playwrightRequest2, "operation.options.value"));
    await page.getByRole("button", { name: "check" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/flows/**");
    await page.getByRole("button", { exact: true, name: "check" }).click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);
    expect(errors).toHaveLength(0);
});
