// Generated by Skyramp v1.3.24 on 2026-06-03 18:48:13.178016001 +0000 UTC m=+511.401689232
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output hash_flow_hmac_config_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/hash_flow_hmac_config_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(182000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));

    await page.goto("http://localhost:8055/admin/login");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.getByRole("button", { name: "edit" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "edit" }).click();
    await page.getByRole("button", { name: "edit" }).click();
    await page.getByRole("checkbox", { name: "check_box_outline_blank" }).click();
    await expect(page.getByRole("button", { name: "Secret Key data_object" })).toContainText("Secret Key");
    await expect(page.getByRole("textbox", { name: "Enter the HMAC secret key..." })).toBeVisible();
    await page.getByRole("textbox", { name: "Enter the HMAC secret key..." }).fill("my-secret-key");
    await expect(page.getByRole("textbox", { name: "Enter the HMAC secret key..." })).toHaveValue("my-secret-key");
    await page.getByRole("button", { name: "check" }).click();
    await page.getByRole("button", { exact: true, name: "check" }).click();
    expect(errors).toHaveLength(0);
});
