// Generated by Skyramp v1.3.27 on 2026-06-24 01:56:41.57381433 +0000 UTC m=+808.022777119
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output search_input_url_state_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/search_input_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(350000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);
    await page.waitForTimeout(3000);
    await expect(page.getByRole("heading", { name: "Active Users" })).toHaveText("Active Users");
    await page.getByRole("button", { name: "search" }).click();
    await page.getByRole("searchbox", { name: "Search Items..." }).fill("admin");
    await page.waitForTimeout(2000);
    await expect(page.getByRole("searchbox", { name: "Search Items..." })).toHaveValue("admin");
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "admin@example.com" })).toHaveText("admin@example.com");
    expect(errors).toHaveLength(0);
});
