// Generated by Skyramp v1.3.27 on 2026-06-24 01:53:22.145067521 +0000 UTC m=+608.594030320
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/filter_toggle_sort_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(830000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/users");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page.getByRole("heading", { name: "Active Users" })).toHaveText("Active Users");

    await page.getByTestId("items-filter-toggle").click();
    await expect(page.getByRole("button", { name: "add Add Filter expand_more" })).toContainText("Add Filter");
    await page.getByTestId("items-filter-toggle").click();
    await page.getByTestId("items-table").getByRole("button", { name: /^First Name/ }).click();
    await page.getByRole("button", { name: "sort Sort Ascending" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("items-table").getByRole("button", { name: "First Name sort" })).toBeVisible();
    await expect(page.getByTestId("items-table").getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "admin@example.com" })).toHaveText("admin@example.com");
    expect(errors).toHaveLength(0);
});
