// Generated by Skyramp v1.3.27 on 2026-06-22 14:49:24.845230527 +0000 UTC m=+642.949768262
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output user_invite_happy_path.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/user_invite_happy_path_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(166000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.getByRole("button", { name: "person_add" }).click();
    await page.getByRole("textbox", { name: "admin@example.com, user@" }).fill("invitetest@testbot.com");
    await page.keyboard.press("Tab");
    await page.getByRole("button", { name: "Invite" }).click();
    await expect(page.getByRole("button", { name: "Invite" })).not.toBeVisible();
    await page.goto("http://localhost:8055/admin/users/invited");
    await page.waitForTimeout(2000);
    await expect(page).toHaveURL(/\/admin\/users\/invited/);
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("row").nth(1)).toContainText("invitetest@testbot.com");
    await expect(errors).toHaveLength(0);
});
