// Generated by Skyramp v1.3.27 on 2026-06-22 14:45:48.838848958 +0000 UTC m=+426.943386713
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output user_invite_validation.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp/app \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/user_invite_validation_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(548000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/login");
    await page.goto("http://localhost:8055");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/users");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/users/invited");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/users");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "person_add" }).click();
    await page.getByRole("textbox", { name: "admin@example.com, user@" }).fill("notanemail");
    await page.keyboard.press("Tab");
    await expect(page.getByText("notanemail: Value has to be a")).toHaveText("notanemail: Value has to be a valid email address");
    await expect(page.getByRole("textbox", { name: "admin@example.com, user@" })).toHaveValue("notanemail");
    await expect(page.getByRole("button", { name: "Invite" })).toBeDisabled();
    await page.getByRole("textbox", { name: "admin@example.com, user@" }).fill("valid@example.com");
    await page.keyboard.press("Tab");
    await expect(page.getByRole("textbox", { name: "admin@example.com, user@" })).toHaveValue("valid@example.com");
    await expect(page.getByRole("button", { name: "Invite" })).toBeEnabled();
    await expect(page.getByText("notanemail: Value has to be a")).not.toBeVisible();
    await expect(errors).toHaveLength(0);
});
