// Generated by Skyramp v1.3.27 on 2026-06-24 01:16:58.655019611 +0000 UTC m=+883.370987037
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output batch_drawer_rollup.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/batch_drawer_rollup_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1446000);

    // set default timeout for all locator/page actions in this test
    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.goto("http://localhost:8055/admin/content/batch_test_items");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/settings/data-model/batch_test_items");
    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.goto("http://localhost:8055/admin/settings/data-model/batch_test_items/+");
    await page.getByRole("button", { exact: true, name: "Input" }).click();

    const playwrightRequest1: Record<string, any> = {"field": "title"};

    await page.getByRole("textbox", { name: "A unique column name..." }).fill(getValue(playwrightRequest1, "field"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/**/**");
    await page.getByRole("button", { name: "Save" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.goto("http://localhost:8055/admin/content/batch_test_items/+");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/settings/data-model/batch_test_items/+");
    await page.getByRole("button", { exact: true, name: "Input" }).click();

    const playwrightRequest2: Record<string, any> = {"field": "title"};

    await page.getByRole("textbox", { name: "A unique column name..." }).fill(getValue(playwrightRequest2, "field"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/**/**");
    await page.getByRole("button", { name: "Save" }).click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.goto("http://localhost:8055/admin/users/+");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest3: Record<string, any> = {"email": "testuser@example.com"};

    await page.getByRole("textbox").nth(2).fill(getValue(playwrightRequest3, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/**");
    await page.getByRole("button", { exact: true, name: "check" }).click();
    const response3 = await responsePromise3;

    // Wait for network activities to finish
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8055/admin/users");
    await page.waitForLoadState('networkidle');
    await page.getByRole("columnheader", { name: "check_box_outline_blank" }).getByRole("checkbox").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("columnheader", { name: "check_box_outline_blank" }).getByRole("checkbox").click();
    await page.getByRole("button", { name: "edit" }).click();
    await expect(page.getByTestId("batch-rollup-header")).toHaveText("0 of 2 succeeded");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise4 = page.waitForResponse("**/**/**");
    await page.getByRole("button", { exact: true, name: "check" }).click();
    const response4 = await responsePromise4;
    expect(response4.status()).toBe(200);
    await expect(page.getByRole("heading", { name: "Active Users" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
