// Generated by Skyramp v1.3.27 on 2026-06-24 01:19:59.841514521 +0000 UTC m=+1064.557481937
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output batch_drawer_initial_state.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/batch_drawer_initial_state_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(112000);

    // set default timeout for all locator/page actions in this test
    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8055/admin/users");
    await page.waitForLoadState('networkidle');
    await page.getByRole("columnheader", { name: "check_box_outline_blank" }).getByRole("checkbox").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("columnheader", { name: "check_box_outline_blank" }).getByRole("checkbox").click();
    await page.getByRole("button", { name: "edit" }).click();
    await expect(page.getByTestId("batch-rollup-header")).toHaveText("0 of 2 succeeded");
    await page.getByRole("button", { exact: true, name: "close" }).click();
    expect(errors).toHaveLength(0);
});
