// Generated by Skyramp v1.3.24 on 2026-05-27 19:08:12.617435821 +0000 UTC m=+280.761695508
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_subtitle_visibility_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/login_subtitle_visibility_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(309000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("Welcome back! Enter your")).toHaveText("Welcome back! Enter your credentials to continue.");
    expect(errors).toHaveLength(0);
});
