// Generated by Skyramp v1.3.24 on 2026-05-27 19:10:28.853925709 +0000 UTC m=+416.998185386
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_sign_in_success_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/login_sign_in_success_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(165000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await expect(page).toHaveURL(/admin\/content/);
    expect(errors).toHaveLength(0);
});
