// Generated by Skyramp v1.3.27 on 2026-06-24 02:40:19.507292507 +0000 UTC m=+780.109466561
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output multi_file_upload_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/multi_file_upload_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(873000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/files");
    await page.waitForTimeout(2000);
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/files/+");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise1 = page.waitForResponse("**/files**");
    // File upload
    const fileChooserPromise0 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Choose File file_upload" }).click();
    const fileChooser0 = await fileChooserPromise0;
    await fileChooser0.setFiles([
        "/home/runner/work/directus/directus/.skyramp/testfiles/test-a.txt",
        "/home/runner/work/directus/directus/.skyramp/testfiles/test-b.txt",
        "/home/runner/work/directus/directus/.skyramp/testfiles/test-c.txt"
    ]);
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/\/admin\/files/);
    await expect(page.getByRole('heading', { name: 'File Library' })).toHaveText('File Library');
    await expect(page.getByRole('button', { name: 'Select All' })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
