// Generated by Skyramp v1.3.27 on 2026-06-23 17:16:24.206707576 +0000 UTC m=+397.339713377
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output tabular_state_machine.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/tabular_state_machine_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(262000);
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/login");
    await page.waitForLoadState('networkidle');

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/users");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // UC04-S1: Before any search query the list region must be idle
    await page.locator('table').waitFor({ state: 'attached', timeout: 20000 });
    await expect(page.locator('.layout-tabular')).toHaveAttribute('data-state', 'idle');

    await page.getByRole("button", { name: "search" }).click();
    await page.getByRole("searchbox", { name: "Search Items..." }).fill("admin");
    // Wait for network activities to finish
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);

    // UC04-S3: On 2xx with results, data-state must be "results"
    await page.locator('table').waitFor({ state: 'attached', timeout: 20000 });
    await expect(page.locator('.layout-tabular')).toHaveAttribute('data-state', 'results');
    await expect(page.getByRole("cell", { name: "admin@example.com" })).toBeVisible();

    await page.waitForTimeout(2000);
    await page.getByRole("searchbox", { name: "Search Items..." }).fill("");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // UC04-C3: Clearing input returns region to idle
    await expect(page.locator('.layout-tabular')).toHaveAttribute('data-state', 'idle');

    expect(pageErrors).toHaveLength(0);
});
