// Generated by Skyramp v1.3.27 on 2026-06-23 17:19:39.162889693 +0000 UTC m=+592.295895484
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output tabular_idle_empty_suspended.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/tabular_idle_empty_suspended_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(153000);
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/users/suspended");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8055/admin/users/suspended");
    await page.waitForLoadState('networkidle');

    // UC04-S1: Suspended Users view — no search term → data-state="idle", no-items slot visible
    await page.locator('.layout-tabular').waitFor({ state: 'attached', timeout: 20000 });
    await expect(page.locator('.layout-tabular')).toHaveAttribute('data-state', 'idle');
    await page.getByRole('heading', { name: 'No Users', level: 2 }).waitFor({ state: 'visible' });
    await expect(page.getByRole('heading', { name: 'No Users', level: 2 })).toBeVisible();
    await expect(page.getByText("There are no users with")).toContainText("There are no users with suspended status.");

    await page.getByRole("button", { name: "search" }).click();
    await page.getByRole("searchbox", { name: "Search Items..." }).fill("xyznonexistentabc");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // UC04-S4: Search with no matches → data-state="empty", no-results slot visible
    await page.locator('.layout-tabular').waitFor({ state: 'attached', timeout: 20000 });
    await expect(page.locator('.layout-tabular')).toHaveAttribute('data-state', 'empty');
    await expect(page.getByRole('heading', { name: 'No Results', level: 2 })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Clear Filters' })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
