// Generated by Skyramp v1.3.27 on 2026-06-24 02:40:19.796210078 +0000 UTC m=+780.398384142
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output upload_dialog_ui_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/upload_dialog_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(229000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8055/admin/files/+");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.getByRole("button", { name: "Done" }).click();
    await expect(page.getByTestId("root").getByText("Items")).toContainText("Items");
    await expect(page).toHaveURL(/\/admin\/files/);
    await expect(page.getByRole('heading', { name: 'File Library' })).toHaveText('File Library');
    expect(pageErrors).toHaveLength(0);
});
