// Generated by Skyramp v1.3.27 on 2026-06-22 20:46:29.64493717 +0000 UTC m=+476.358004731
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output wizard_navigation_steps.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/wizard_navigation_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(476000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.goto("http://localhost:8055/admin/settings/data-model/+");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8055/admin/login");
    await page.getByRole("button", { name: "Continue" }).click();
    await page.getByRole("textbox", { name: "A unique table name..." }).fill("test_wizard_nav");
    await expect(page.getByRole("textbox", { name: "A unique table name..." })).toHaveValue("test_wizard_nav");
    await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByRole("button", { name: "Back" })).toBeVisible();
    await page.getByRole("button", { name: "Back" }).click();
    await expect(page.getByRole("textbox", { name: "A unique table name..." })).toHaveValue("test_wizard_nav");
    expect(errors).toHaveLength(0);
});
