// Generated by Skyramp v1.3.27 on 2026-06-22 20:46:30.786912183 +0000 UTC m=+477.499979734
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output wizard_three_step_submit.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/wizard_submit_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(103000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    await page.goto("http://localhost:8055/admin/login");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("password");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.getByRole("textbox", { name: "A unique table name..." }).fill("test_wizard_s2_verify");
    await page.getByRole("button", { name: "Next" }).click();
    await page.getByRole("button", { name: "Next" }).click();
    await page.getByRole("button", { name: "Finish Setup" }).click();
    await expect(page).toHaveURL(/test_wizard_s2_verify/);
    await expect(page.getByRole("heading", { name: "Test Wizard S2 Verify" })).toHaveText("Test Wizard S2 Verify");
    expect(errors).toHaveLength(0);
});
